//All The Common Types for Users module

export interface Batch_Subjects {
    batchId: number,
    subjects: { subjectId: number, subject: string }[]
}

export interface Subject {
    subjectId: number,
    subject: string
}

export interface Course {
    courseId: number,
    course: string,
    batches: Batch[]
}

export interface Batch {
    batchId: number,
    batch: string
}

export interface Lecture {
    batches_subjects: BatchesSubjects[]
    datetime: string
    downloadable: boolean
    lectureSRC: string
    lectureType: string
    onlineLectureId: number
    title: string
    typeId: number
}

export interface BatchesSubjects {
    subject: string,
    batch: string,
    fromTime: string,
    toTime: string,
}

export interface Permissions {
    see_exam: number,
    new_exam: number,
    add_exam_subjects: number,
    edit_exam: number,
    delete_exam: number,
    insert_marks: number,
    edit_marks: number,
    view_reports: number,
    new_assignment: number,
    see_assignment: number,
    edit_assignment: number,
    delete_assignment: number,
    new_noticeboard: number,
    see_noticeboard: number,
    edit_noticeboard: number,
    delete_noticeboard: number,
    add_subject: number,
    edit_subject: number,
    delete_subject: number,
    see_subjects: number,
    add_question: number,
    edit_question: number,
    delete_question: number,
    see_questions: number,
    add_test: number,
    edit_test: number,
    delete_test: number,
    see_tests: number,
    preview_test: number,
    regenerate_result: number,
    publish_test: number,
    view_reports_of_all: number,
    view_reports_of_assigned: number,
    add_course: number,
    edit_course: number,
    delete_course: number,
    see_course: number,
    see_assigned_course_subjects: number,
    assign_course_subjects: number,
    deassign_course_subjects: number,
    add_online_lecture: number,
    edit_online_lecture: number,
    delete_online_lecture: number,
    see_online_lecture: number,
    sort_online_lecture: number,
    send_sms_by_number: number,
    send_sms_by_batch: number,
    view_finished_lectures: number,
    reception: number,
    add_student: number,
    edit_student: number,
    delete_student: number,
    see_student: number,
    see_student_mobile: number,
    open_student_account: number,
    approve_disapprove_students: number,
    add_user: number,
    edit_user: number,
    delete_user: number,
    see_user: number,
    see_assigned_user_batches: number,
    assign_user_batches: number,
    deassign_user_batches: number,
    see_assigned_user_subjects: number,
    assign_user_subjects: number,
    deassign_user_subjects: number,
    open_user_account: number,
    default_permissions: number,
    candidate_portal: number,
    add_fees: number,
    see_fees: number,
    edit_fees: number,
    delete_fees: number,
    approve_disapprove_fees: number,
    see_student_attendance: number,
    set_student_attendance: number,
    edit_student_attendance: number,
    see_others_attendance: number,
    see_todays_attendance: number,
    set_users_timings: number,
    add_books: number,
    edit_books: number,
    delete_books: number,
    see_books: number,
    return_issue_books: number,
    assign_work: number,
    see_accept_reject_leave: number,
    content_management_system: number,
    see_scheduled_classes: number,
    edit_scheduled_classes: number,
    cancel_scheduled_classes: number,
    delete_scheduled_classes: number,
    add_class_schedule: number
}


const permissionsObject = {
    see_exam: null,
    new_exam: null,
    add_exam_subjects: null,
    edit_exam: null,
    delete_exam: null,
    insert_marks: null,
    edit_marks: null,
    view_reports: null,
    new_assignment: null,
    see_assignment: null,
    edit_assignment: null,
    delete_assignment: null,
    new_noticeboard: null,
    see_noticeboard: null,
    edit_noticeboard: null,
    delete_noticeboard: null,
    add_subject: null,
    edit_subject: null,
    delete_subject: null,
    see_subjects: null,
    add_question: null,
    edit_question: null,
    delete_question: null,
    see_questions: null,
    add_test: null,
    edit_test: null,
    delete_test: null,
    see_tests: null,
    preview_test: null,
    regenerate_result: null,
    publish_test: null,
    view_reports_of_all: null,
    view_reports_of_assigned: null,
    add_course: null,
    edit_course: null,
    delete_course: null,
    see_course: null,
    see_assigned_course_subjects: null,
    assign_course_subjects: null,
    deassign_course_subjects: null,
    add_online_lecture: null,
    edit_online_lecture: null,
    delete_online_lecture: null,
    see_online_lecture: null,
    sort_online_lecture: null,
    send_sms_by_number: null,
    send_sms_by_batch: null,
    view_finished_lectures: null,
    reception: null,
    add_student: null,
    edit_student: null,
    delete_student: null,
    see_student: null,
    see_student_mobile: null,
    open_student_account: null,
    approve_disapprove_students: null,
    add_user: null,
    edit_user: null,
    delete_user: null,
    see_user: null,
    see_assigned_user_batches: null,
    assign_user_batches: null,
    deassign_user_batches: null,
    see_assigned_user_subjects: null,
    assign_user_subjects: null,
    deassign_user_subjects: null,
    open_user_account: null,
    default_permissions: null,
    candidate_portal: null,
    add_fees: null,
    see_fees: null,
    edit_fees: null,
    delete_fees: null,
    approve_disapprove_fees: null,
    see_student_attendance: null,
    set_student_attendance: null,
    edit_student_attendance: null,
    see_others_attendance: null,
    see_todays_attendance: null,
    set_users_timings: null,
    add_books: null,
    edit_books: null,
    delete_books: null,
    see_books: null,
    return_issue_books: null,
    assign_work: null,
    see_accept_reject_leave: null,
    content_management_system: null,
    see_scheduled_classes: null,
    edit_scheduled_classes: null,
    cancel_scheduled_classes: null,
    delete_scheduled_classes: null,
    add_class_schedule: null
}

export { permissionsObject }